#!/bin/bash

# postinst script for wlanthermo

# restart sudo service
systemctl restart sudo 

# enable lighttpd module
lighty-enable-mod auth

if [ -f /etc/lighttpd/lighttpd.conf ]
then
    echo Backing up old lighttpd.conf
    mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.bak
fi

mv /var/www/conf/lighttpd.conf /etc/lighttpd/lighttpd.conf

# check if new web password has been set
if [ -f /var/www/tmp/update ]
then
    echo 'Password found!'
    passwort=`cat /var/www/tmp/update`
    echo "$passwort"
    htpasswd -c -b /etc/lighttpd/htpasswd wlanthermo $passwort
    rm /var/www/tmp/update # Updateflag zuruecksetzen
elif [ -f /etc/lighttpd/htpasswd ] && egrep -q '^wlanthermo' /etc/lighttpd/htpasswd
then
    echo 'Password already set!'

elif [ -t 0 ]
then
    echo 'No password found!'
    echo 'Please enter the new password for user >wlanthermo< of the protected area!'
    htpasswd -c /etc/lighttpd/htpasswd wlanthermo
else
then
    echo 'No password found!'
    echo 'Setting default password >raspberry<'
        htpasswd -c -b /etc/lighttpd/htpasswd wlanthermo raspberry
fi

# Update configuration
/usr/bin/wlt_2_updateconfig.py

ln -s /var/log/WLAN_Thermo /var/www/thermolog &> /dev/null
ln -s /var/log/WLANThermo.log /var/www/log/WLANThermo.log &> /dev/null
chown -R www-data:www-data /var/www &> /dev/null
chown -R www-data:www-data /var/log/WLAN_Thermo &> /dev/null

chown root:root /etc/sudoers.d/WLANThermo &> /dev/null
chmod 0440 /etc/sudoers.d/WLANThermo &> /dev/null

# Reload new unit files
systemctl daemon-reload

# enable all required services
systemctl enable WLANThermo.service
systemctl enable WLANThermoWD.service
systemctl enable pigpiod.service
systemctl enable nextion_hwclock.service

# Restart services
systemctl restart lighttpd.service
systemctl restart WLANThermo.service
systemctl start pigpiod.service
systemctl restart WLANThermoWD.service
