#! /bin/sh
# postinst script for wlanthermo

# enable all required services
systemctl enable WLANThermo.service
systemctl enable WLANThermoWD.service
systemctl enable pigpiod.service

# restart sudo service
systemctl restart sudo 

# enable lighttpd module
lighty-enable-mod auth

if [ -f /etc/lighttpd/lighttpd.conf ]
then
    echo Backing up old lighttpd.conf
    mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.bak
fi

mv /var/www/conf/lighttpd.conf /etc/lighttpd/lighttpd.conf

# check if new web password has been set
if [ -f /var/www/tmp/update ]
then
    echo 'Passwort gefunden!'
    passwort=`cat /var/www/tmp/update`
    echo "$passwort"
    htpasswd -c -b /etc/lighttpd/htpasswd wlanthermo $passwort
    rm /var/www/tmp/update # Updateflag zuruecksetzen
else
    echo 'Kein Passwort gefunden!'
    echo 'Jetzt das Passwort für den Benutzer >wlanthermo< des geschützten Bereichs eingeben!'
    htpasswd -c /etc/lighttpd/htpasswd wlanthermo
fi

ln -s /var/log/WLAN_Thermo /var/www/thermolog
chown -Rv www-data:www-data /var/www 1>/dev/null
chown -Rv www-data:www-data /var/log/WLAN_Thermo 1>/dev/null

chmod 0440 /etc/sudoers.d/WLANThermo

# Reload new unit files
systemctl daemon-reload

# Restart services
systemctl restart lighttpd
systemctl restart WLANThermo
systemctl restart WLANThermoWD
systemctl start pigpiod.service
