#!/bin/sh
# Starts and stops WLANThermo Pitmaster
# von Joe16
### BEGIN INIT INFO
# Provides:          WLANThermoPIT
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     
# Default-Stop:      0 1 6
# Short-Description: Startet WLANThermo Pitmaster
# Description:       Startet WLANThermo Pitmaster
### END INIT INFO

DAEMON=/usr/bin/python
ARGS=/usr/sbin/wlt_2_pitmaster.py
DAEMON_NAME=WLANThermoPIT

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/wlt_2_pitmaster.pid

. /lib/lsb/init-functions
 
do_start () {
log_daemon_msg "Starting system $DAEMON_NAME daemon"
#start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --startas $DAEMON
/sbin/start-stop-daemon --start --pidfile $PIDFILE \
        --user root --group root \
        -b \
        --chuid root \
        --exec $DAEMON $ARGS
log_end_msg $?
}
do_stop () {
log_daemon_msg "Stopping system $DAEMON_NAME daemon"
#start-stop-daemon --stop --pidfile $PIDFILE --retry 10
 /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
log_end_msg $?
}

case "$1" in
 
start|stop)
do_${1}
;;
 
restart|reload|force-reload)
do_stop
do_start
;;
 
status)
status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
;;
*)
echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|restart|status}"
exit 1
 ;;
 
esac
exit 0
